apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: info
  namespace: flux-system
spec:
  interval: 10m
  path: ./clusters/homelab/apps/info
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
