apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homepage
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: homepage
      sourceRef:
        kind: HelmRepository
        name: homepage-charts
        namespace: flux-system
      version: "1.0.0" # Replace with actual version
  values:
    service:
      type: LoadBalancer
    ingress:
      enabled: true
      className: nginx
      hosts:
        - host: home.int.rosair.me
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - home.int.rosair.me
          secretName: homepage-tls
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                    - mac-mini
                    - macbook-pro
    tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"