apiVersion: ENC[AES256_GCM,data:MzM=,iv:ahelyfnOT8jaqPAUuyiJcrSAgd4O3q92L1OM+2QHU0Y=,tag:SzZF6EQO+VFHyL5vB3QpCg==,type:str]
kind: ENC[AES256_GCM,data:aXZlOh/n,iv:/aS0CbY1sN/K+e9G1hbTCVhyDoVdDtgCf99WkDC3/l8=,tag:EHPQHAaB3B9rXQaUCGfWcg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:W7vRWm/ngj+s9m+6lw==,iv:+186aP8YeMRX16qG3VjmKNSLhQMlsAuX9rNues0NAlQ=,tag:g4UOjbRMU4UePfYxHV+Kjw==,type:str]
    namespace: ENC[AES256_GCM,data:dwYubQ==,iv:8Y2agTQZ8f/UlDoS/7jd4/DYSsf0hUk/PNdEChOVQO0=,tag:rlkrxt15WS1uJLtCzJAF3A==,type:str]
data:
    token: ENC[AES256_GCM,data:96B6GlAHtr6ToRT0i6YxBcPq4qUkwbislje7mlA=,iv:+YlihO4kuK9Z1V1ROnf4sC72rzabWlfepSo4nmlxRuU=,tag:WEgk3/kBqIEIdublXaihIQ==,type:str]
sops:
    lastmodified: "2025-05-24T11:36:01Z"
    mac: ENC[AES256_GCM,data:LYRpe/bWZ6NQv/7eCNehRQOjfxu3TGMRjLr5+GqZ+HYSsgq+q0bCncbGxl4uF9HkqFTadVmchYJLTjyARK+PsEamuyeILzPm+HGWWj4r9MrAlY9LUrbJW7hQ0pHVYyPPsG3OKOeB8sbxxG/4uRlKeFcreMn1X8jNx+j9zWb+IWs=,iv:7w6xF+IsPFvdHOHZNna83Ph4GTMD2lI4Y1tgqD0Hc/w=,tag:KwYp1ZuKPtN6Dl788uBF1g==,type:str]
    pgp:
        - created_at: "2025-05-24T11:36:01Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D4YlNfiXbedkSAQdAz0TDYlv4tWIfnI/3l5C+LMC+l5EJIDtEeOVokjwfvU0w
            YfpbUKLgg55rzrAwQ5g1iLtgNAgjHjnCLl5Cq6/RWGyAOOs6CCXsrF3U889mhRUa
            1FsBCQIQR9VHlSxHCIqzxw6TMxJkj5XE15MJ5WKIuynE/lpHlvkUhxjWNFtm+x6Z
            h8pqF+Al36nBynih47TlL809iwxw3xha2q3h32kmJtHkOQ7KYTozJ6kPe3AP
            =+vNl
            -----END PGP MESSAGE-----
          fp: B7D08F8ECF1C7697
    unencrypted_suffix: _unencrypted
    version: 3.10.2
