apiVersion: ENC[AES256_GCM,data:jP4=,iv:fFGNOPGkk1TZ+mxDTLiigGe3SJgnbWnG3uYq5PF9ags=,tag:ylKcTfOcOTZCe/2A0lwDiw==,type:str]
kind: ENC[AES256_GCM,data:KUi3Uaul,iv:PqaEpefAS9CPy60Me9ZH3H+LrmAk246vDc9oi9W5hvE=,tag:3z27EghAvEOx4eghf1JcuA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:VIzXbnOznlUZ3e3ZrmRouw==,iv:J9R9pgJTPwhoNiXe5qRNdqb36Wc1mmLDMdkVwLf1n6Q=,tag:1XKeDGnSVBjMMa3Xo9DPwA==,type:str]
    namespace: ENC[AES256_GCM,data:2CH2TA==,iv:stz3CWf1gd1NlueOlfX7w1syCViycqNVd7foE4QpDow=,tag:cZJpP3Xt30d+72X5jURHbw==,type:str]
type: ENC[AES256_GCM,data:G4zONuAS,iv:Tuz+ZZpedXntZVsr7HiDt1gjizXIgDNsqsk6A2AtZoo=,tag:eMLLu7kP5Xne7Uf6PAQZoQ==,type:str]
data:
    claimToken: ENC[AES256_GCM,data:mGBcHvEXD4TP+94jIAuQsU8VAAjItgIFSK5LPsSavTiJEfLT,iv:y2V7UeUc0Jb9+gymIy1aBRTqrlZYcp41cc7YXFpJol8=,tag:vznIWhblbOUbTqUsyPGRZg==,type:str]
sops:
    lastmodified: "2025-05-24T12:01:20Z"
    mac: ENC[AES256_GCM,data:aLNtVIv3DdoY/nHfwXaaHV5wnTmn6nT5GA5WI8XsK+Gc4Vv98iQZIpaT9aVB95TUq1+faHBFBap7/FmfBHJJXWGLX+8OIuJPn3iGtCnTKz+wPWu5eDnQ8FvMw7OerN7EycAmvz3/ehqrAcak+ymGI4W9I3ifDs22CN4ohyv77LY=,iv:qP5IHQdJ7oX3AYkbbh3CKIf3uuYDiGurChsqAXl+7pw=,tag:sy8egC6bIKYaWC9fqqbDcw==,type:str]
    pgp:
        - created_at: "2025-05-24T12:01:20Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D4YlNfiXbedkSAQdAoQDNgBEFXEqGrIC2EqjnBv2CF5iAh0H22gFZ9J/8iEcw
            lWr2H12CN9+6+soct/EDYZnKdabnI4anphFP2sv46+Evg1QmYEZSlMaKNR1JUnSu
            1GgBCQIQzqMycEewbVGjEd0o1PbvyVcnZ8pUdxErzrsUWgHJppXQccToexf/BJnC
            hDaOQp/Ais/bh6yeC+FIvrQCJnfvYSolsVl5Dt+oGJdbktKQOg4qJ8hIZGtzIHAE
            CTMuYSYqGTKkOw==
            =Ik9l
            -----END PGP MESSAGE-----
          fp: B7D08F8ECF1C7697
    unencrypted_suffix: _unencrypted
    version: 3.10.2
