---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgC0+ACvlyd/i9mfQoOJ5n+1O6lFOlHdb6/kwIFvAdxxrSV/AeWLCNoid2ErHJjCWwYzoeKF99c4nLhNa09zLWAgAtnNLbhczQH2kOhKqB/kFpqWpPrXSyXZjmta9i+PsNZtN/7k3e7blbP+zwcMEIW6d2lNDia8QttnSxwD1JrY9RWebnJcMK/CUIOIV0lLT6ePRTtV7/Azj3OfqM8Yo8UZCCy5H8J1ZJeEOvDoIw6mtV0bQp/tI29xL18FwmHurwcgYybmInmRoLxZmEHoeYQ5LIT+Dek2Dt5yz5WYDSb2GR094ZlmHRKOTNlkaK8TCIApvGsSJKWHrPoGbdIN163mZhJdx8zJ0xkU4p1/xj0lHgBZdQAbyOFM/YrgnHD0nnz+yJW+XB5mvLk4sBWj+st2QUxsRNhYekr2ee/HWFSEtUa6pgHl3JMwSyEmjTBQi2scv16oPuzzn6DXp1BwFkxqUOb9Dh1c8YXjwvfpPQ3/IZEnsKUM0ZYk93SWZN9nu+2JBGByMHSO11l8Yd5h7Q51JVFj8WNFz2T1doVvc7TCzr8Qs5Zdkb5JNtnBpHvNJi1wGDlc3FgDl//PM+t9zHh1AjdC22pcl0ex4UUTeypNvENzIjUReWOpaAHvAsnNn6sPb6gQZQMaqERwmMDOCMr2eePavOsXPjgOCMnLWU9Dhrd9ymYjW38OcQfw6Q4AYo2sRAVbBj3eMB3Y7hheBwXvbhfrf1ZKkE3shiK3X3g6B/MC3EIRtTLH
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: cert-manager
    type: Opaque
