apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: example-token
  namespace: info
spec:
  encryptedData:
    token: AgA...REDACTED
  template:
    metadata:
      name: example-token
      namespace: info
    type: Opaque
