apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: podinfo
  namespace: info
spec:
  interval: 30m
  chart:
    spec:
      chart: podinfo
      version: "6.5.2"
      sourceRef:
        kind: HelmRepository
        name: podinfo
        namespace: info
  values:
    ingress:
      enabled: true
      className: nginx
      hosts:
        - host: info.int.rosair.au
          paths:
            - path: /
              pathType: Prefix
