apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: reloader
  namespace: reloader
spec:
  interval: 30m
  chart:
    spec:
      chart: reloader
      version: "v1.0.51"
      sourceRef:
        kind: HelmRepository
        name: stakater
        namespace: reloader
  values: {}
