apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudflare-tunnel
  namespace: cloudflare
spec:
  interval: 30m
  chart:
    spec:
      chart: cloudflared
      version: "0.2.0"
      sourceRef:
        kind: HelmRepository
        name: cloudflare
        namespace: cloudflare
  values:
    tunnel:
      credentials: {}
