resources:
  - namespace.yaml
  - helmrepository.yaml
  - helmrelease.yaml
patches:
  - target:
      kind: HelmRelease
      name: authentik
    patch: |
      spec:
        values:
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: kubernetes.io/hostname
                        operator: In
                        values:
                          - macbook-pro
                          # - mac-mini
          tolerations:
            - key: "node-role.kubernetes.io/control-plane"
              operator: "Exists"
              effect: "NoSchedule"
            - key: "node-role.kubernetes.io/worker"
              operator: "Exists"
              effect: "NoSchedule"
