apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: plex
  namespace: plex
spec:
  interval: 1h
  chart:
    spec:
      chart: plex
      version: "1.0.0"
      sourceRef:
        kind: HelmRepository
        name: plex-charts
        namespace: flux-system
  values:
    existingSecret: plex-claim-token
    persistence:
      config:
        enabled: true
        size: 5Gi
      data:
        enabled: true
        size: 50Gi
    service:
      type: NodePort
      nodePort: 32400
    ingress:
      enabled: true
      hosts:
        - host: plex.int.rosair.me
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - plex.int.rosair.me
          secretName: plex-tls